### ISSUE TITLE
Missing query message by cliMsgId

### ISSUE THREAD

**Issue by jonnywilliamson** [arcturial/clickatell#15] opened 2015-09-28 09:19 UTC
Hi,

Thanks for the package. It appears that there's possibily a missing method for querying a message status.

The [docs here](https://www.clickatell.com/help/apidocs/Message.htm#QueryMsgStatus) state

>Query the status of a message

>This command enables the user to query both the status and charge of a delivered message.You can query the status with either the 'apimsgid' or 'climsgid'

>Endpoint: https://api.clickatell.com/rest/message/[apiMessageId] OR >https://api.clickatell.com/rest/message?clientMessageId=<some_id>

>HTTP Method: GET

Notice there are 2 ways to get a message query,

1) If you know the apiMessageId, you can use this package.
2) If you only have your cliMsgId, there's currently no way to query a message status.

I can either send you a PR with my idea on how to fix it, or you might be more familiar with your code and prefer to implement this in the way you see fit.

At the moment the interface has 

```php
/**
     * API call for "getMsgCharge".
     *
     * @param string $apiMsgId ApiMsgId to query
     *
     * @throws Exception
     *
     * @return mixed
     */
    public function getMessageCharge($apiMsgId);
}
```

Which isn't really correct, The interface should support either supplying a apiMsgId OR a cliMsgId.

What would you like me to do? Thanks for your help.

**Comment by arcturial** [comment] 2015-09-28 09:55
You are welcome to submit a PR, I would probably just change the interface to `getMessageCharge($msgId, $clientMsgId = false);` and based on the value of the second parameter either use API message ID or client message ID. If you don't have time, I will try and get to the change as soon as I can. Nice catch.

**Comment by jonnywilliamson** [comment] 2015-09-28 09:56
I'm about 90% finished with my PR. Will send shortly.

**Comment by arcturial** [comment] 2015-09-28 13:35
new tag (2.1.3) pushed

I left in the "id" field in the response which is just a duplicate of "apiMsgId". This is so we can support backwards compatibility for now. It can be removed in the next minor patch.

**Closed by arcturial** 2015-09-28 13:35 UTC

**Comment by jonnywilliamson** [comment] 2015-09-28 13:37
Thanks.
